apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  labels:
    app: homeassistant
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123

      nodePort: 31099
