apiVersion: v1
kind: Service
metadata:
  name: homeassistantservice
  namespace: homeassistant    # <- Aquí debe ir un namespace válido
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
  type: NodePort



