apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistantpvc
  namespace: homeassistant  # <-- asegúrate que este namespace exista
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


