apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
  labels:
    app: homeassistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:2024.6
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: homeassistantpvc



